version: '2'
services:
  golang:
    image: golang:latest
    user: $UID:$GID
    volumes:
      - $PWD:/work
      - go-data:/go
    working_dir: /work
    ports:
      - "4660:8080"
    entrypoint: go
    environment:
      - GOCACHE=/go
      - GOPATH=/work

volumes:
  go-data:
