#!/usr/bin/env bash

set -e

IMAGE=elixir:1.13-alpine
MIX_VOLUME_NAME=mix-data
MIX_VOLUME_PATH=/mix
HEX_VOLUME_NAME=hex-data
HEX_VOLUME_PATH=/hex

if ! docker volume inspect $MIX_VOLUME_NAME > /dev/null 2>&1; then
  docker volume create $MIX_VOLUME_NAME
  docker run --rm -v $MIX_VOLUME_NAME:$MIX_VOLUME_PATH --name init-$MIX_VOLUME_NAME $IMAGE chmod 777 $MIX_VOLUME_PATH
fi

if ! docker volume inspect $HEX_VOLUME_NAME > /dev/null 2>&1; then
  docker volume create $HEX_VOLUME_NAME
  docker run --rm -v $HEX_VOLUME_NAME:$HEX_VOLUME_PATH --name init-$HEX_VOLUME_NAME $IMAGE chmod 777 $HEX_VOLUME_PATH
fi

docker run \
  -it --rm \
  -u $(id -u):$(id -g) \
  -v mix-data:$MIX_VOLUME_PATH \
  -v hex-data:$HEX_VOLUME_PATH \
  -v $PWD:/work \
  -w /work \
  -e "MIX_HOME=$MIX_VOLUME_PATH" \
  -e "HEX_HOME=$HEX_VOLUME_PATH" \
  $IMAGE \
  iex $@
  #bash
